CREATE TABLE [dbo].[CUSTOMER_RECORDS] (
    [NO]          INT            IDENTITY (1, 1) NOT NULL,
    [MEMBER_ID]   INT   NOT NULL,
	[DATE_Y]   INT   NOT NULL,
	[DATE_M]   INT   NOT NULL,
	[DATE_D]   INT   NOT NULL,
	[COST]   INT   NOT NULL,
    [CONTENT] NVARCHAR (MAX) NOT NULL,
    [MODIFY_DATE]    DATETIME       NOT NULL,
	[MODIFY_USER]    DATETIME       NOT NULL,
    PRIMARY KEY CLUSTERED ([NO] ASC)
);

